{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls,service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scaling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Desired Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}"
      }
     ]
    },
    {
     "title": "Current Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}",
       "legendFormat": "Desired"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}",
       "legendFormat": "Min"
      }
     ]
    },
    {
     "title": "Min Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}"
      }
     ]
    },
    {
     "title": "Max Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$service_name\", horizontalpodautoscaler=\"keda-hpa-$service_name\"}"
      }
     ]
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_duration_count{service_name=\"$service_name\"}[2m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_duration_count{service_name=\"$service_name\", http_status_code=~\"[45]..\"}[2m])) by(http_status_code)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(rate(traces_spanmetrics_duration_bucket{service_name=\"$service_name\"}[2m])) by (le)\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(traces_spanmetrics_duration_bucket{service_name=\"$service_name\"}[2m])) by (le)\n)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(traces_spanmetrics_duration_bucket{service_name=\"$service_name\"}[2m])) by (le)\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"$service_name\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Trazas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trazas",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "filters": [
        { "id": "773befc3", "operator": "=", "scope": "span" },
        {
         "id": "service-name",
         "isCustomValue": false,
         "operator": "=",
         "scope": "resource",
         "tag": "service.name",
         "value": [ "$service_name" ],
         "valueType": "string"
        }
       ],
       "limit": 20,
       "metricsQueryType": "range",
       "tableType": "traces"
      }
     ]
    }
   ]
  }
 ]
}