{{- if .Values.app.migrations.enabled }}
{{- if not .Values.app.migrations.args }}
{{- fail "You must specify the migration command at '.app.migrations.args'" }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: {{ include "application.fullname" . }}-{{ randNumeric 5 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "-3"
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrations
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}
            - secretRef:
                name: {{ include "application.fullname" . }}
          {{- with .Values.app.migrations.extraEnvs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
          {{- with .Values.app.migrations.args }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.migrations.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}