apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
type: Opaque
stringData:
{{- with .Values.app.secretEnv }}
  {{- toYaml . | nindent 2 }}
{{- end }}
