resources: 
  - apiVersion: v1
    kind: Secret
    metadata:
      name: wagtail-db-password
      labels:
        cnpg.io/reload: "true"
    type: kubernetes.io/basic-auth
    stringData:
      username: wagtail
      password: wagtail-password
  - apiVersion: postgresql.cnpg.io/v1
    kind: Cluster
    metadata:
      name: wagtail-db-cluster
    spec:
      instances: 1
      imageName: ghcr.io/cloudnative-pg/postgresql:16
      imagePullPolicy: IfNotPresent
      postgresUID: 26
      postgresGID: 26
      storage:
        size: 8Gi
      primaryUpdateMethod: switchover
      primaryUpdateStrategy: unsupervised
      logLevel: info
      enableSuperuserAccess: true
      managed:
        roles:
          - login: true
            name: wagtail
            passwordSecret:
              name: wagtail-db-password
  - apiVersion: postgresql.cnpg.io/v1
    kind: Database
    metadata:
      name: wagtail-db-cluster-wagtail
    spec:
      name: wagtail
      cluster:
        name: wagtail-db-cluster
      ensure: present
      owner: wagtail
      template: template1
      encoding: UTF8
      databaseReclaimPolicy: retain