receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

exporters:
  logging:
    verbosity: detailed
  otlphttp:
    metrics_endpoint: "http://mimir:9009/otlp"
    logs_endpoint: "http://loki:3100/otlp"
    traces_endpoint: "http://tempo:4318/v1/traces"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlphttp]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlphttp]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, otlphttp]