receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

connectors:
  spanmetrics:
    namespace: otel
    histogram:
      explicit:
        buckets: [250ms, 500ms, 750ms, 1s, 5s, 10s]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code

exporters:
  file/metrics:
    path: /var/otel/file-exporter/metrics.json
  file/logs:
    path: /var/otel/file-exporter/logs.json
  file/traces:
    path: /var/otel/file-exporter/traces.json
  logging/metrics:
    verbosity: detailed
  logging/logs:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  otlphttp:
    metrics_endpoint: "http://mimir:9009/otlp"
    logs_endpoint: "http://loki:3100/otlp"
    traces_endpoint: "http://tempo:4318/v1/traces"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [memory_limiter, batch]
      exporters: [logging/metrics, file/metrics, otlphttp]
    logs:
      receivers: [otlp, fluentforward]
      processors: [memory_limiter, batch]
      exporters: [logging/logs, file/logs, otlphttp]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging/traces, otlphttp, file/traces, spanmetrics]