minio:
  enabled: false

distributor:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ingester:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

querier:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

query_frontend:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

query_scheduler:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

compactor:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

store_gateway:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

mimir:
  structuredConfig:
    limits:
      max_global_exemplars_per_user: 100000
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: mimir-alerts
        endpoint: minio.minio.svc:9000
        access_key_id: mimir
        secret_access_key: mimir12345
        insecure: true
    ruler_storage:
      backend: s3
      s3:
        bucket_name: mimir-ruler
        endpoint: minio.minio.svc:9000
        access_key_id: mimir
        secret_access_key: mimir12345
        insecure: true
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-chunks
        endpoint: minio.minio.svc:9000
        access_key_id: mimir
        secret_access_key: mimir12345
        insecure: true