fullnameOverride: redmine

imagePullSecrets:
  - name: github-registry

app:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/redmine/app
    tag: latest
  port: 3000
  staticDir: /usr/src/redmine/public
  fileDir: /usr/src/redmine/files
  migrations:
    args:
      - redmine-migrate
  env:
    REDIS_URL: "redis://redmine-redis-valkey/0"
    REDMINE_DB_MYSQL: redmine-db-mysql-cluster-db-mysql
    REDMINE_DB_DATABASE: redmine
    REDMINE_DB_USERNAME: redmine
    OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.opentelemetry:4318
    OTEL_SERVICE_NAME: redmine-demo
    OTEL_PROPAGATORS: tracecontext,baggage
    FLUENTD_URL: http://opentelemetry-collector.opentelemetry:8006/redmine-demo
  secretEnv:
    REDMINE_DB_PASSWORD: redmine-password
    REDMINE_SECRET_KEY_BASE: "10f4e6ef0ebed745be6889fd22931d119f6017a57864142912b739090561c17d48b19c370b90090c"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  livenessProbe:
    httpGet:
      path: /health_check/site
      port: app
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 4
  readinessProbe:
    httpGet:
      path: /health_check/site
      port: app
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 4

persistence:
  enabled: true
  size: "5Gi"
  accessMode: ReadWriteMany
  storageClass: nfs

nginx:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/redmine/nginx
    tag: latest
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

autoscaling:
  enabled: true
  prometheusServerAddr: http://mimir-gateway.mimir.svc/prometheus
  triggers:
    - metricName: request-rate
      threshold: "10"
      query: >
        sum(
          rate(
            traces_spanmetrics_calls{service_name="{{ .Values.app.env.OTEL_SERVICE_NAME }}"}[2m]
          )
        )