fullnameOverride: wagtail

imagePullSecrets:
  - name: github-registry

app:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/wagtail/app
    tag: latest
  port: 8000
  staticDir: /app/bakerydemo/collect_static
  fileDir: /app/bakerydemo/media
  extraPostStartCommands:
    - python manage.py collectstatic
    - python manage.py load_initial_data
    - cp /app/bakerydemo/media/original_images/* /app/bakerydemo/media/images
  migrations:
    args:
      - wagtail-migrate
    volumes:
  livenessProbe: null
  readinessProbe: null
  extraEnvs:
    - name: DATABASE_URL
      value: postgres://$(DATABASE_USERNAME):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)
  env:
    REDIS_URL: redis://wagtail-redis-valkey/0
    DJANGO_SETTINGS_MODULE: bakerydemo.settings.custom
    OTEL_SERVICE_NAME: wagtail-demo
    OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.opentelemetry:4318
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_PROPAGATORS: tracecontext,baggage
    OTEL_PYTHON_LOG_CORRELATION: "true"
    OTEL_PYTHON_LOG_FORMAT: "%(msg)s [span_id=%(span_id)s]"
    OTEL_PYTHON_LOG_LEVEL: debug
    OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: "true"
    OTEL_LOG_LEVEL: debug
    DATABASE_USERNAME: wagtail
    DATABASE_NAME: wagtail
    DATABASE_HOST: wagtail-db-cluster-rw
  secretEnv:
    DATABASE_PASSWORD: wagtail-password
    DJANGO_SECRET_KEY: changeme

persistence:
  enabled: true
  size: "5Gi"
  accessMode: ReadWriteMany
  storageClass: nfs

nginx:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/wagtail/nginx
    tag: latest
  staticMountPath: /app/bakerydemo/static
  livenessProbe: null
  readinessProbe: null

route:
  enabled: true
  tracing:
    enabled: false
  hostnames:
    - wagtail.localhost
  parentRefs:
    - name: nginx
      namespace: nginx-gateway
      sectionName: http