fullnameOverride: wordpress

imagePullSecrets:
  - name: github-registry

app:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/wordpress/app
    tag: latest
  port: 9000
  fileDir: /var/www/html
  migrations:
    enabled: false
  init:
    enabled: true
    image:
      repository: wordpress
      tag: cli-2.12.0-php8.3
    command:
      - sh
      - -c
    args:
      - 'wp core install --url="$WORDPRESS_URL" --title="$WORDPRESS_TITLE" --admin_user="$WORDPRESS_ADMIN_USER" --admin_password="$WORDPRESS_ADMIN_PASSWORD" --admin_email="$WORDPRESS_ADMIN_EMAIL" --skip-email'
  livenessProbe: null
  readinessProbe: null
  env:
    WORDPRESS_DB_HOST: wordpress-db-mysql-cluster-db-mysql
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DEBUG: "true"
    WORDPRESS_CONFIG_EXTRA: |
      define('WP_DEBUG_LOG', '/dev/stderr');
      define('WP_DEBUG_DISPLAY', false);
    WORDPRESS_TITLE: "Wordpress Demo"
    WORDPRESS_ADMIN_USER: demo
    WORDPRESS_URL: http://wordpress.localhost
    # OTel auto instrumentation config
    # https://opentelemetry.io/docs/instrumentation/php/automatic/#installation
    OTEL_PHP_AUTOLOAD_ENABLED: "true"
    OTEL_SERVICE_NAME: wordpress-demo
    OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector.opentelemetry:4318
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
  secretEnv:
    WORDPRESS_DB_PASSWORD: wordpress-password
    WORDPRESS_AUTH_KEY: "random-key"
    WORDPRESS_SECURE_AUTH_KEY: "random-key"
    WORDPRESS_LOGGED_IN_KEY: "random-key"
    WORDPRESS_NONCE_KEY: "random-key"
    WORDPRESS_AUTH_SALT: "random-key"
    WORDPRESS_SECURE_AUTH_SALT: "random-key"
    WORDPRESS_LOGGED_IN_SALT: "random-key"
    WORDPRESS_NONCE_SALT: "random-key"
    WORDPRESS_ADMIN_PASSWORD: demo
    WORDPRESS_ADMIN_EMAIL: demo@example.com

persistence:
  enabled: true
  size: "5Gi"
  accessMode: ReadWriteMany
  storageClass: nfs

nginx:
  image:
    repository: ghcr.io/lucasdc6/tesis-demo-apps/wordpress/nginx
    tag: latest

route:
  enabled: true
  tracing:
    enabled: true
  hostnames:
    - wordpress.localhost
  parentRefs:
    - name: nginx
      namespace: nginx-gateway
      sectionName: http