---
volumes:
  wordpress:

networks:
  app:
  backend:
  observability:

services:
  wordpress:
    image: wordpress
    build:
      context: ..
      dockerfile: container_files/Containerfile.wordpress
      target: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress-password
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', '/dev/stderr');
        define('WP_DEBUG_DISPLAY', false);

      # OTel auto instrumentation config
      # https://opentelemetry.io/docs/instrumentation/php/automatic/#installation
      OTEL_PHP_AUTOLOAD_ENABLED: true
      OTEL_SERVICE_NAME: wordpress-demo
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
    volumes:
      - wordpress:/var/www/html
    networks:
      - app
      - backend
      - observability

  wordpress-nginx:
    image: wordpress-nginx
    build:
      context: ..
      dockerfile: container_files/Containerfile.wordpress
      target: nginx
    environment:
      UPSTREAM_HOST: wordpress:9000
    volumes:
      - wordpress:/var/www/html:ro
    networks:
      - app