---
volumes:
  redmine_public:
  redmine_data:

networks:
  app:
  backend:
  observability:

services:
  redmine: &redmine
    image: redmine
    build:
      context: ..
      dockerfile: container_files/Containerfile.redmine
      target: redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine-password
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: redmine-demo
      FLUENTD_URL: http://otel-collector:8006/redmine-demo
    volumes:
      - redmine_data:/usr/src/redmine/files
      - redmine_public:/usr/src/redmine/public
    networks:
      - app
      - backend
      - observability

  redmine-migrations:
    <<: *redmine
    ports: []
    command:
      - redmine-migrate
    networks:
      - app
      - backend
      - observability

  redmine-nginx:
    image: redmine-nginx
    build:
      context: ..
      dockerfile: container_files/Containerfile.redmine
      target: nginx
    environment:
      UPSTREAM_HOST: redmine:3000
    depends_on:
      - redmine
    volumes:
      - redmine_public:/usr/share/nginx/html:ro
    networks:
      - app