---
volumes:
  db:
  mimir:
  loki:
  tempo:

networks:
  app:
  backend:
  observability:

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - db:/var/lib/mysql
      - ./etc/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

  lb:
    image: nginx:1.26.0
    environment:
      WORDPRESS_HOST: wordpress-nginx
      WORDPRESS_SERVER_NAME: wordpress.localhost
      REDMINE_HOST: redmine-nginx
      REDMINE_SERVER_NAME: redmine.localhost
      WAGTAIL_HOST: wagtail-nginx
      WAGTAIL_SERVER_NAME: wagtail.localhost
      GRAFANA_HOST: grafana:3000
      GRAFANA_SERVER_NAME: grafana.localhost
    volumes:
      - ./etc/nginx/00-lb-entrypoint.sh:/docker-entrypoint.d/00-lb-entrypoint.sh:ro
      - ./etc/nginx/lb.conf.template:/tmp/lb.conf.template:ro
      - ./etc/nginx/grafana.conf.template:/etc/nginx/templates/grafana.conf.template:ro
    networks:
      - app
      - observability
    ports:
      - 80:80

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.1
    volumes:
      - ./etc/otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    networks:
      - observability

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./etc/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    networks:
      - observability

  mimir:
    image: grafana/mimir:main-011c02fbc
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - mimir:/var/mimir
      - ./etc/grafana/mimir.yaml:/etc/mimir.yaml:ro
      - ./etc/grafana/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml:ro
    networks:
      - observability

  loki-init:
    image: &lokiImage grafana/loki:main-9767807
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/loki"
    volumes:
      - loki:/var/loki

  loki:
    image: *lokiImage
    command: ["-config.file=/etc/loki.yaml"]
    volumes:
      - ./etc/grafana/loki.yaml:/etc/loki.yaml
      - loki:/var/loki
    networks:
      - observability
    depends_on:
      - loki-init

  tempo-init:
    image: &tempoImage grafana/tempo:main-17c5e7d
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/grafana/tempo.yaml:/etc/tempo.yaml
      - tempo:/var/tempo
    networks:
      - observability
    depends_on:
      - tempo-init
