apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    version: 1
    editable: false
    uid: mimir
    isDefault: true
    jsonData:
      httpMethod: "POST"
      exemplarTraceIdDestinations:
        - datasourceUid: "tempo"
          name: "traceID"
      alertmanagerUid: "alertmanager"
  - name: Mimir Alertmanager
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://mimir:9009
    version: 1
    editable: false
    uid: alertmanager
    jsonData:
      implementation: "mimir"
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    version: 1
    editable: false
    uid: loki
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    version: 1
    editable: false
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: mimir