bases:
  - ./bases/repositories.yaml
---
releases:
  - name: gateway-api-crds
    disableValidationOnInstall: true
    namespace: kube-system
    wait: true
    chart: ../charts/gateway-api-crd
  - name: nginx-gateway-fabric
    wait: true
    namespace: nginx-gateway
    version: 2.4.*
    disableValidationOnInstall: true
    chart: nginx/nginx-gateway-fabric
    values:
      - values/gateway-api.yaml
    needs:
      - kube-system/gateway-api-crds
