bases:
  - ./bases/repositories.yaml
  - ./bases/environments.yaml
---
releases:
  - name: keda
    namespace: keda
    chart: kedacore/keda
    version: 2.19.*
    values:
      - values/keda/values.yaml
