bases:
  - ./bases/repositories.yaml
---
releases:
  - name: mysql-operator
    namespace: mysql-operator
    chart: bitpoke/mysql-operator
    version: 0.6.*
    values:
      - ./values/mysql-operator.yaml
  - name: cnpg
    namespace: cnpg
    chart: cnpg/cloudnative-pg
    version: 0.27.*