repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: lgtm-distributed
    namespace: observability
    chart: grafana/lgtm-distributed
    version: 2.1.*
    values:
      - values/lgtm-distributed.yaml