bases:
  - ./bases/repositories.yaml
  - ./bases/environments.yaml
---
releases:
  - name: ganesha-nfs
    chart: ganesha-nfs/nfs-server-provisioner
    namespace: ganesha-nfs
    version: 1.8.*
    values:
      - values/ganesha/values.yaml
