bases:
  - ./bases/repositories.yaml
---
releases:
  ##################
  # Redmine
  ##################
  - name: redmine-regcred
    namespace: redmine
    chart: jitterbit/dockerconfigjson
    version: 1.0.*
    secrets:
      - values/github-registry.yaml
  - name: redmine-db
    namespace: redmine
    chart: bitpoke/mysql-cluster
    version: 0.6.*
    values:
      - values/redmine-db.yaml
  - name: redmine
    namespace: redmine
    chart: ../../helm
    values:
      - values/redmine.yaml
    needs:
      - redmine/redmine-regcred
      - redmine/redmine-db
  ##################
  # Wordpress
  ##################
  - name: wordpress-regcred
    namespace: wordpress
    chart: jitterbit/dockerconfigjson
    version: 1.0.*
    secrets:
      - values/github-registry.yaml
  - name: wordpress-db
    namespace: wordpress
    chart: bitpoke/mysql-cluster
    version: 0.6.*
    values:
      - values/wordpress-db.yaml
  - name: wordpress
    namespace: wordpress
    chart: ../../helm
    values:
      - values/wordpress.yaml
    needs:
      - wordpress/wordpress-regcred
      - wordpress/wordpress-db
  ##################
  # Wagtail
  ##################
  - name: wagtail-regcred
    namespace: wagtail
    chart: jitterbit/dockerconfigjson
    version: 1.0.*
    secrets:
      - values/github-registry.yaml
  - name: wagtail-db
    namespace: wagtail
    chart: bedag/raw
    values:
      - values/wagtail-db.yaml
  - name: wagtail-redis
    namespace: wagtail
    chart: valkey/valkey
    version: 0.9.*
  - name: wagtail
    namespace: wagtail
    chart: ../../helm
    values:
      - values/wagtail.yaml
    needs:
      - wagtail/wagtail-regcred
      - wagtail/wagtail-db
      - wagtail/wagtail-redis