bases:
  - ./bases/repositories.yaml
  - ./bases/environments.yaml
---
releases:
  - name: locust
    namespace: locust
    chart: locust/locust
    version: 0.34.*
    values:
      - values/locust/values.yaml
      - values/locust/extra-objects.yaml.gotmpl
